---
title: "VBA Script for removing alpha characters from a string of alphanumeric text"
author: "Leon Shpaner"
date: "2020-11-13"
output: html_document
math: true
---

```{r setup, include=FALSE, attr.source='.numberLines'}
knitr::opts_chunk$set(echo = TRUE)
```

Copy the following code into the VBA Environment in excel:

<br>

<html>

<style>
p.indent {
    text-indent: 30px;
}

div.a {
  line-height:130%;
}


</style>
</head>
<body>

<div class="a"> <p style="font-family:consolas"> <font color = blue> Sub </font color>  RemoveAlphas()
<br> <font color = green> \'\' Remove alpha characters from a string </font color>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color = blue> Dim </font color> intI <font color = blue> As Integer </font color> 
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim strNotNum <font color = blue> As String </font color>, strTemp <font color=blue> As String </font color>
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue>Set</font color> rngRR = Selection.SpecialCells(xlCellTypeConstants, _
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; xlTextValues)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color = blue> For Each </font color> rngR <font color=blue> In </font color> rngRR
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strTemp = \"\"
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> For </font color> intI = 1 <font color=blue>To</font color> Len(rngR.Value)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue>If</font color> Mid(rngR.Value, intI, 1) <font color=blue>Like</font color> \"[0-9]\" <font color=blue> Then </font color>
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strNotNum = Mid(rngR.Value, intI, 1)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue>Else</font color>: strNotNum = \" \"
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> End If </font color>
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strTemp = strTemp & strNotNum
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> Next </font color> intI
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; rngR.Value = strTemp
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue>Next</font color> rngR

<font color=blue>End Sub</font color>
</p>

</div>
</body>
</html>







