---
title: ""
author: "Leon Shpaner"
date: "2017-11-13"
output: html_document
image:
  caption: ''
  focal_point: ''
  preview_only: yes
---

> #### BONDS: Solving Fixed Income Problems via Finance & Excel
> Shpaner, Leon - University of California, San Diego - Financial Modeling with Excel
>
>
> 

<iframe width="100%" height="700" frameborder="0" scrolling="no" src="https://onedrive.live.com/embed?resid=A5FB65B6C9763D08%2133922&authkey=%21ALmMiJqCwzmHnsM&em=2&AllowTyping=True&wdInConfigurator=True"></iframe>


> Complete the following tasks (based on the principles shown in the text book, instructor learning materials as well your own prior course work):
>
> 1)	Briefly describe the implications of each of the hypotheses (expectations, liquidity and segmentation) when the yield curve is (a) upward sloping and (b) downward sloping.
>
>> **Expectations hypothesis:**
>> **Long term bond yields are geometric averages of present and expected future values. These averages will vary for different maturities unless the expected future rates are equal to the current rates.  In this hypothesis, there is no risk premium built into the bond prices.**
>>
>> **a)	Upward sloping – The upward sloping curve is a result of expected future short rates exceeding the current (present) short rate**
>>
>> **b)	Downward sloping – the downward sloping yield curve shows that the expected future short rates are lower than the current (present) short rate.**
>>
>> **The different yields to maturities are explained by the expected values of future short rates differing from the current present value of the short rate.**
>>
>> **Liquidity hypothesis:**
>> **The overall implication from this hypothesis is that bonds of varying maturities are able to have different yields despite the fact that expected short rates are equal to the current short rate; thus FV = PV. This occurs because the yields on long-term >> bonds exceed the expected returns (future values) from rolling over short term bonds. AS the maturity increases, so do interest rates. This is done in order to provide a type of compensation to investors for taking on a premium (risk) on interest rate.** 
>>
>> **a)	Upward sloping – if liquidity premiums are significant enough, the upward sloping yield curve remains in line with expectations of falling short rates.**
>>
>> **b)	Downward sloping – future short rates are lower than the current short rates (where FV<PV), assuming that liquidity premiums are positive.**
>>
>> **Segmentation hypothesis**
>>
>> **The market is segmented, and therefore, each investor has their own preferred maturity sector. Here, the interest rates on bonds are governed by independent supply and demand conditions from each respective sector. The varying curves from this hypothesis are shown by a disproportion between supply and demand for bonds of varying maturities.  As such,**
>>
>> **a)	an upward sloping yield curve shows that there is a significant push in the long-term market, and subsequent push on the demand in the short term market.**
>>
>> **b)	an increase in short-term rates does not effect long-term rates**
>
> 2)	You are considering purchase of a 10% coupon interest, 10-year bond with a par value of $1,000.
>
> (a)	Use Excel to compute the price you should pay for this bond assuming semi-annual interest payments and 8% yield to maturity.
>
>>
>> **The price of the bond, assuming semi-annual interest payments and 8% yield to maturity is $1,135.90 => '#2a - Price of Bond'!B8**
>
> (b)	One year from now, you expect that the yield to maturity for this bond to be 6%.  Use Excel to compute the realized compound yield during the year while assuming a reinvestment rate of 5% and semi-annual interest payments.
> 
>> **The realized compound yield (RCY) during the year while assuming a reinvestment rate of 5% and semi-annual interest payment is 21.17%**
>
> (c)	Identify and comment on the significance of each of the components of the calculated realized compound yield from results in part “b.”
>
>> **In part b, the following is calculated: a) price movement, and b) the coupon payment and reinvestment.**
>> **First, the price of the bond at (T +1) was calculated, and we already know the (T+0) price of $1,135.90 from question #2a). At (T+1), we have 18 payments of $50.00 remaining at 3%. The future value is still $1,000, so our Present value (PV) is >>calculated to be $1,275.07. Therefore, this is the price of the bond at (T+1). At (T+1), a coupon payment of $50.00 is received. Moreover, half way through the year at (T + 0.5), we get a payment of $50.00, and this gets re-invested at 2.5%, because that is 5% for half a year (semi – annual), totaling $51.25.**
**So, once again, at (T+1), the bond went up by $139.17 in price value. This number was calculated by subtracting the starting price of $1135.90 from the present value of $1,275.07. Therefore, the total value of the coupons is calculated to be 50 + 51.25 (that is 50 at (t+1) right on the spot where there is no time to reinvest, and 50 at (t+0.5) where we had half a year to reinvest).**
>>
>> **Calculating the total return, we have $139.17 + 50 + 51.25 = $240.42, which yields 21.17% ( = 240.42/1135.90).**
>>
>> **In this example, it is important to understand the relationship between interest rates and prices. When interest rates go down, bond prices go up. This is due to the fact that the bond’s interest payments will be greater than the amounts available in new bonds issued at current market interest rates.**
>
> **The learning goals from this assignment are:**
>
> Familiarize yourself with the mechanics of Bond valuation, maturities and interest yields; refinement of interpretive skills with respect to calculated financial outcomes.

