---
title: "VBA - script for converting formulas in an excel workbook to values across all worksheets"
author: "Leon Shpaner"
date: 2020-11-13
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Copy the following code into the VBA Environment in excel:

<br>

<html>

<style>
p.indent {
    text-indent: 30px;
}

div.a {
  line-height:130%;
}


</style>
</head>
<body>

<div class="a"> <p style="font-family:consolas"> <font color = blue> Sub </font color>  ConvertFormulasToValuesAllWorksheets()

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color = blue> Dim</font color> ws <font color=blue> As</font color>  Worksheet, rng  </font color> <font color=blue> As </font color> Range
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> For Each </font color> ws <font color=blue> In </font color> ActiveWorkbook.Worksheets
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> For Each </font color> rng <font color=blue> In </font color> ws.UsedRange
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> If </font color> rng.HasFormula <font color=blue> Then </font color>
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; rng.Formula = rng.Value
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> End If </font color>
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> Next </font color> rng
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color=blue> Next </font color> ws

<font color = blue> End Sub </font color> 

</p>

</div>
</body>
</html>