---
title: "California Geothermal Wells"
author: "Leon Shpaner"
date: "2020-08-17"
output: html_document
image:
  caption: ''
  focal_point: ''
  preview_only: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following visualization shows county by county numbers (quantity) of Geothermal Wells in the State of CA. This data was sourced independently from the [CALGem ArcGIS Hub open data](https://hub.arcgis.com/datasets/d639eb012fe142c89ea8ac779a665ca5_1/data?geometry=-119.036%2C32.448%2C-114.284%2C33.255) and linked directly to Tableau using [Javascript](https://leonshpaner.com/datasets/ca_geothermal_data/cageothermalwells.js) and html to produce this [web data connector](https://leonshpaner.com/datasets/ca_geothermal_data/cageothermalwells.html) whose button is clickable within the Tableau environment.

Herein, it is interesting to note that out of the total number of 4,235 records of geothermal wells in the state of California, Imperial County boasts 1,523, Sonoma County - 748, and Lake County with an impressive 617 for third place. These top 3 counties account for roughly 68% of all geothermal wells in the state, regardless of Well Status (activity level). As seen immediately in the accompanying dashboard below, many counties are also entirely omitted from this infographic. As such, it is almost safe to assume that data does not exist in these regions, or they are physically lacking in these resources.

Taking a deeper dive into the data, we can also see that Chevron U.S.A., Inc., Geysers Power Company LLC, and Freeport-McMoRan, boast 528, 485, and 315 wells respectively, as the top 3 operators in the state of California.

In the last button of the storyboard, we can take the raw data for what it's worth and drill down according to our needs on an experiment basis. For example, if we wanted to look at only active wells, the *"WellStatus"* filter *A* would yield only 1,372 results, so only 32% of geothermal wells are active. 260 (roughly 6%) of these wells have also proven to be idle, denoted by *"WellStatus I".* Other statuses like B,C,N,P, and U remain to be defined by the resource provider. 

Now, if we were to filter out our top producing operator, Chevron U.S.A, we can also immediately see that 435 out of the 528 wells belong to Imperial County - an alarming 82%.



<iframe seamless frameborder="0" src="https://public.tableau.com/views/CAGeothermalWells/GeothermalWellsinCA-inNumberandDensity?:language=en&:display_count=y&:showVizHome=no" width = '100%' height = '1100'></iframe> 
