---
title: ""
author: "Leon Shpaner"
date: "2017-10-27"
output: html_document
image:
  caption: ''
  focal_point: ''
  preview_only: yes
---

> #### Two Stock Portfolio - Expected Returns, Standard Deviaiton, Variance, and Coefficient of Variation 
> Shpaner, Leon - University of California, San Diego - Financial Modeling with Excel
>
>
> 

<iframe width="100%" height="700" frameborder="0" scrolling="no" src="https://onedrive.live.com/embed?resid=A5FB65B6C9763D08%2133914&authkey=%21AE1BJAkRRKsCFug&em=2&AllowTyping=True&wdInConfigurator=True"></iframe>

> PORTFOLIOS: Return & Risk via Finance & Excel
> Complete the following tasks (based on the principles shown in the text book, instructor learning materials as well your own prior course work):
>
> Calculate the expected returns, standard deviations and coefficient of variations of a two-stock portfolio. We have the following data for Stock 'C' and Stock 'S'.
> 
  +-------------------------+------------+------------+
  |                         |            |            |
  |                         | Stock C    | Stock S    |
  +-------------------------+------------+------------+
  |                         |            |            |
  | Expected Return         | 11%        | 25%        |
  +-------------------------+------------+------------+
  |                         |            |            |
  | Standard   Deviation    | 15%        | 20%        |
  +-------------------------+------------+------------+
  |                         |                         |
  | Correlation             |          0.3            |
  +-------------------------+-------------------------+
>
> Note: For calculation of expected returns, standard deviations and coefficient of variations, assume the following allocation mix to run a multiple scenario analysis.
> 
 |     Weight Stock C      |     100%    |     80%    |     60%    |     40%    |     20%    |      0%     |
 |-------------------------|:-----------:|:----------:|:----------:|:----------:|:----------:|:-----------:|
 |  **Weight Stock S**     |  **0%**     |  **20%**   | **40%**    | **60%**    | **80%**    | **100%**    |
>
> In sum, your tasks are to calculate Expected Return, Standard Deviation and Coefficient of Variation for each of these scenarios using your own Excel model. 
>
> For extra-credit, graph your calculated results. 😃
>
> The learning goals from this assignment are:
> Develop competency in calculating expected return and risk metrics for a multi-asset portfolio [in this instance and for exercise purposes, a two-asset portfolio].
