---
title: "UCLA Fall Undergraduate Enrollment Trends (1999-2019)"
author: "Document Author"
date: "2020-07-28"
output:
  pdf_document: default
  html_document: default
  word_document: default
subtitle: A Hypothesis Test 
highlight: true
header:
  image: ""
---

<p>UCLA Undergraduate Fall Enrollment numbers have been averaging 27,340 for the last 20 years (1999-2019), with an average 1.26% growth rate year over year. A noticeable milestone was reached in 2017 when the population of new students crossed the 31k mark. Notwithstanding, from 2018-2019 we have seen a reduction of 0.11% from 31,577 down to 31,543 new student enrollments. Given the current state of COVID-19 physical distancing restrictions, coupled with the slight drop off between 2018-2019, the question we should be asking is will we be seeing a notable decrease in new student enrollments from 2019-2020?</p>
<p>To shed more light on potential outcomes for this scenario, we will conduct the following hypothesis test:</p>
<p><span class="math inline">\(\small{H_0:}\)</span> (initial hypothesis): the number of students enrolled in 2020 will be at least 30,000 <span class="math inline">\({\large\hspace{2mm}\Longrightarrow{\hspace{2mm}}}\)</span> <span class="math inline">\(\small {H_0: \mu \geq 30,000}\)</span></p>
<p><span class="math inline">\(\small{H_a:}\)</span> (alternative hypothesis): the number of students enrolled in 2020 will exceed 30,000 <span class="math inline">\({\large\Longrightarrow{\hspace{2mm}}}\)</span> <span class="math inline">\(\small {H_a: \mu \neq 30,000}\)</span></p>
<p>The last 20 years’ worth of data are observed with actual fall enrollment numbers (source: <a href="https://www.universityofcalifornia.edu/infocenter/fall-enrollment-glance" class="uri">https://www.universityofcalifornia.edu/infocenter/fall-enrollment-glance</a>). The average number of enrolled students is measured as 27340.48 from the 21 observations. In order to test these numbers, a z-value measuring the difference between the average (mean) of the last 20 years’ observations and our null (initially hypothesized value) must be calculated. This mathematical value is expressed in the following:</p>
<p><span class="math inline">\(\small{TS = z = \large\frac{\overline{x} - x_o}{SE_\overline{x}}{\hspace{2mm}\Longrightarrow{\hspace{2mm}}}}\)</span>
<span class="math inline">\(\small SE_\overline{x} = \large\frac{s}{\sqrt{n}}{\hspace{2mm}\Longrightarrow{\hspace{2mm}}} \normalsize \small TS = (27340.48 - 30000)\cdot\large\frac{\sqrt{21}}{2443.37} = \small -4.988\)</span></p>
<p>where <span class="math inline">\(\overline{x}\)</span> = mean,<span class="math inline">\({\hspace{2mm}}x_o\)</span> = mean from the null and <span class="math inline">\(\small {SE_\overline{x}}\)</span> = standard error</p>
<p>Prior to conducting the test, comments must be made about the potential downside risk of the false positive and false negative errors. A Type 1 (false positive) error would indicate that we have rejected the null hypothesis when it was indeed true. To mitigate this risk, we will assume an alpha (critical p-value) of 0.05. This is chosen based on a wider, yet common 95% confidence level where P = 1 – 0.95 = 0.05 (the probability that the null hypothesis is true). Using this large confidence level will ultimately allow a wider range of data, with enough “wiggle room” for a larger margin of error. In determining any potential Type 2 (false negative) errors, we may run the risk of not rejecting our null (initial hypothesis) by not factoring in a large enough sample size. The mitigation to this possible problem would be to get a larger sample size.</p>
<p>Finally, the hypothesis test is conducted as follows using R.</p>
<p>First, we load the library (readr) so we can load the csv file “UCLAEnrollment” that contains our data set into a dataframe called enrollment.</p>
<pre class="r"><code>library(readr)
enrollment = read.csv(&quot;UCLAEnrollment.csv&quot;)</code></pre>
<p>To see the data set, we proceed to view(enrollment) which loads this into R environment. A quick summary gives us a glance at the minimum and maximum, median, mean, as well as the 1st and 3rd quartiles of each variable in the data set.</p>
<pre class="r"><code>View(enrollment)
summary(enrollment)</code></pre>
<pre><code>##       Year         Enrolled         Delta          
##  Min.   :1999   Min.   :24668   Min.   :-0.029900  
##  1st Qu.:2004   1st Qu.:25328   1st Qu.:-0.001225  
##  Median :2009   Median :26536   Median : 0.016200  
##  Mean   :2009   Mean   :27340   Mean   : 0.012555  
##  3rd Qu.:2014   3rd Qu.:29585   3rd Qu.: 0.026475  
##  Max.   :2019   Max.   :31577   Max.   : 0.043500  
##                                 NA&#39;s   :1</code></pre>
<p>To help us better understand the characteristics of the enrollment figures, let us view the summary statistics of this variable.</p>
<p>It becomes apparent that the average number of enrolled students year over year is roughly 27,340.</p>
<pre class="r"><code>mean(as.numeric(enrollment$Enrolled, na.rm = TRUE))</code></pre>
<pre><code>## [1] 27340.48</code></pre>
<p>with a standard deviation of 2,443.369.</p>
<pre class="r"><code>sd(as.numeric(enrollment$Enrolled, na.rm = TRUE))</code></pre>
<pre><code>## [1] 2443.369</code></pre>
<p>The minimum number of enrolled students in the Fall from 1999-2019 was 24,668.</p>
<pre class="r"><code>min(as.numeric(enrollment$Enrolled, na.rm = TRUE))</code></pre>
<pre><code>## [1] 24668</code></pre>
<p>with a maximum number in the same category expressed as 31,577.</p>
<pre class="r"><code>max(as.numeric(enrollment$Enrolled, na.rm = TRUE))</code></pre>
<pre><code>## [1] 31577</code></pre>
<p>To see this trend represented using a line plot, the ggplot library is loaded and the code executed as follows:</p>
<pre class="r"><code>library(ggplot2)
knitr::opts_chunk$set(fig.width=25, fig.height=8) 
options(repr.plot.width = 1, repr.plot.height = 8)
ggplot(data = enrollment[1:2], aes(x=Year, y=Enrolled, group = 3))+
  expand_limits(x=2020, y=32000)+
  geom_line(color =&quot;#2a63ff&quot;, size=2, alpha=0.9, linetype=1)+
  theme_bw()+
  labs(title = &quot;Enrolled&quot;,
       x = &quot;\nYear&quot;,
       y = &quot;Number Enrolled \n&quot;)+
  ggtitle(&quot;UCLA Undergraduate Fall Student Enrollment (1999-2019)&quot;)</code></pre>
<p><img src="/post/portfolio/UCLAEnrollment/index_files/figure-html/fig1-1.png" width="1920" /></p>
<p>From the line plot alone, we can gather that enrollment numbers have been trending upward year over year for the last 20 years. However, to answer our original question: “will we be seeing a notable decrease in new student enrollments from 2019-2020?” a t test with a confidence level of 95% is conducted below. Here, we are surmising that enrollment numbers will be greater than or equal to 30,000. Alternatively, we are postulating that the numbers will fall below 30,000. Let us now see the results by plugging in the statistics we have calculated manually earlier:</p>
<pre class="r"><code>xbar = 27340.48
mu0 = 30000.00
sigma = 2443.37
n = 21
z = (xbar-mu0)/(sigma/sqrt(n))
z</code></pre>
<pre><code>## [1] -4.987968</code></pre>
<p>The z-value of -4.988 still holds true from our prior manual test, and when calculated against alpha, we retrieve the critical value as follows</p>
<pre class="r"><code>alpha = 0.05
z.alpha = qnorm(1-alpha)
# The critical value (-z.alpha)is shown below
-z.alpha</code></pre>
<pre><code>## [1] -1.644854</code></pre>
<p>The test statistic -4.988 is lower than the critical value of -1.645. Therefore, at a 0.05 significance level, we must reject our initial claim that student enrollment will reach or exceed 30,000 in the fall of 2020.</p>
<pre class="r"><code># t test of x against a null hypothesis

t.test(enrollment$Enrolled, mu = 30000, conf.level = 0.95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  enrollment$Enrolled
## t = -4.988, df = 20, p-value = 7.066e-05
## alternative hypothesis: true mean is not equal to 30000
## 95 percent confidence interval:
##  26228.27 28452.68
## sample estimates:
## mean of x 
##  27340.48</code></pre>
<p>As evident from the t-test above, the p-value of 3.553e-05 is statistically significant, and falls substantially below the alpha level of 0.05. As such, we must also reject the idea or notion that Fall Student Enrollment in 2020 will equal or surpass that of 30,000 students (the null hypothesis).</p>
